project:
  type: website
  output-dir: ../../docs

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Setup and Installation"
        file: Documentation.qmd
      - text: "Model Creation and Deployment"
        file: Model_workflow.qmd
      - text: "Resources"
        file: Resources.qmd
